server:
  port: 8182

spring:
  application:
    name: validation

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true # Optional, for preferring IP address in registration