# application.yml

server:
  port: 8080 # or your preferred port

spring:
  application:
    name: ISPServer

eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false