# application.yml

server:
  port: 8761 # or your preferred port

spring:
  application:
    name: eureka-app

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
  instance:
    leaseRenewalIntervalInSeconds: 10
  dashboard:
    enabled: true